### ISSUE TITLE
希望优化快进、增加快退自定义时间

### ISSUE THREAD

**Issue by hot36952** [x1ao4/plex-mpv#1]
目前默认快进快退10s，快退可以稳定-10s，但是每次快进会随机+10s+(0~3)s，不稳定+10s。
1，希望优化。
2，修改成更短时间如3s、5s，快进会更不稳定，同样希望优化
3，希望增加快退，支持自定义时间

**Comment by x1ao4** [comment]
我已经在最新版本 [v1.4](https://github.com/x1ao4/plex-mpv/releases/tag/v1.4) 中增加了**快退**脚本，你可以下载使用。

如需自定义**快进**或**快退**的时长，请用文本编辑/记事本打开 `skipForward-keybinds.lua` 或 `skipBackward-keybinds.lua` 脚本，将 `seek 10` 或 `seek -10` 中的 `10` 修改为你期望的秒数并保存即可（重启后生效）。

在播放时通过 plex-mpv 的快进脚本快进，确实可能会出现 `10+` 秒的快进，不一定是正好 `10` 秒，可能会多一两秒，但如果你把视频暂停，然后快进，应该就是正好 `10` 秒的快进，可能是由于播放器机制的问题，或者有其他原因，但脚本中设置的时长就是 `10` 秒整，所以这个问题我目前无法解决（不知道原因）。

你可以通过自定义快进或快退时长来设置一个你认为合适的时长。
